export interface PatientFormData {
  first_name: string;
  last_name: string;
  date_of_birth: string;
  gender: string;
  email: string;
  phone: string;
  address: string;
  height_cm: string; 
  weight_kg: string;   
  allergies: string;   
  medical_notes: string;
}

export interface Patient {
  id: number; // Assuming ID is generated by DB
  first_name: string;
  last_name: string;
  date_of_birth: string;
  gender: string;
  email: string | null;
  phone: string | null;
  address: string | null;
  height_cm: number | null;
  weight_kg: number | null;
  allergies: string | null;
  medical_notes: string | null;
  created_at: string;
}